name: lugu_pet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  refreshed: 2.7.0
  dartz: 0.10.1
  http: 1.2.1
  shared_preferences: 2.2.3
  logging: 1.2.0
  intl: 0.19.0
  firebase_core: 2.32.0
  firebase_messaging: 14.9.4
  firebase_crashlytics: 3.5.7
  flutter_local_notifications: 17.1.2
  # package_info_plus: 8.0.0
  carousel_slider_x: 5.0.2
  flutter_svg: 2.0.10+1
  universal_html: 2.2.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_flavorizr: 2.2.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

flavorizr: 
  app: 
    android: 
      flavorDimensions: flavor-type
  flavors: 
    development: 
      app: 
        name: SkyKomik Dev
      android: 
        applicationId: id.my.skydemo.komik.dev
        variables: 
          FLUTTER_TARGET: 
            value: lib/main_dev.dart
      linux: 
        bundleId: id.my.skydemo.komik.dev
        variables: 
          FLUTTER_TARGET: 
            value: lib/main_dev.dart
      windows: 
        bundleId: id.my.skydemo.komik.dev
        variables: 
          FLUTTER_TARGET: 
            value: lib/main_dev.dart
    production: 
      app: 
        name: SkyKomik
      android: 
        applicationId: id.my.skydemo.komik
        variables: 
          FLUTTER_TARGET: 
            value: lib/main_prod.dart
      linux: 
        bundleId: id.my.skydemo.komik
        variables: 
          FLUTTER_TARGET: 
            value: lib/main_prod.dart
      windows: 
        bundleId: id.my.skydemo.komik
        variables: 
          FLUTTER_TARGET: 
            value: lib/main_prod.dart

