// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUjNCMslgbcRiNdgSqBw0rYyF8h04kaVs',
    appId: '1:925616653905:web:788949cead2f6141049a70',
    messagingSenderId: '925616653905',
    projectId: 'skykomik',
    authDomain: 'skykomik.firebaseapp.com',
    storageBucket: 'skykomik.appspot.com',
    measurementId: 'G-TS62D0S5KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpTTdr-VFEm2arR9cGE_IAKAyfwvLHDfA',
    appId: '1:925616653905:android:ea354eea10fc0812049a70',
    messagingSenderId: '925616653905',
    projectId: 'skykomik',
    storageBucket: 'skykomik.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUjNCMslgbcRiNdgSqBw0rYyF8h04kaVs',
    appId: '1:925616653905:web:bc1fa058509bcc15049a70',
    messagingSenderId: '925616653905',
    projectId: 'skykomik',
    authDomain: 'skykomik.firebaseapp.com',
    storageBucket: 'skykomik.appspot.com',
    measurementId: 'G-L7VS8VZ701',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzBsdIU2uObPvGf3GerLROwcFsj8E4IN0',
    appId: '1:925616653905:ios:33c5d06e07c4e294049a70',
    messagingSenderId: '925616653905',
    projectId: 'skykomik',
    storageBucket: 'skykomik.appspot.com',
    iosBundleId: 'pet.lugu.id.luguPet',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzBsdIU2uObPvGf3GerLROwcFsj8E4IN0',
    appId: '1:925616653905:ios:33c5d06e07c4e294049a70',
    messagingSenderId: '925616653905',
    projectId: 'skykomik',
    storageBucket: 'skykomik.appspot.com',
    iosBundleId: 'pet.lugu.id.luguPet',
  );

}